name: ProjectPrinter
on: [push]
jobs:
  build: 
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, ubuntu-24.04-arm]

    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.101

      - name: Build
        run: dotnet build /p:EnableWindowsTargeting=true
      - name: Publish Linux
        if: matrix.platform == 'ubuntu-latest'
        run: dotnet publish --self-contained --runtime linux-x64 -c Release
      - name: Publish Windows
        if: matrix.platform == 'windows-latest'
        run: dotnet publish --self-contained --runtime win-x64 -c Release
      - name: Publish Linux ARM
        if: matrix.platform == 'ubuntu-24.04-arm'
        run: dotnet publish --self-contained --runtime linux-arm64 -c Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: ProjectPrinter-${{ matrix.platform }}
          path: |
            ProjectPrinter/bin/Release/net9.0/*-*/*
            device_config/bin/Release/net9.0/*-*/*


